" leader \

" exmap upSkipFold jsfile   .obsidian/vimrc-helper.js {moveUpSkipFold()}
" exmap downSkipFold jsfile .obsidian/vimrc-helper.js {moveDownSkipFold()}
" nmap k :upSkipFold
" nmap j :downSkipFold

" mapping next/previous heading
exmap nextHeading jsfile .obsidian/vimrc-helper.js {jumpHeading(true)}
exmap prevHeading jsfile .obsidian/vimrc-helper.js {jumpHeading(false)}
nmap ]] :nextHeading
nmap [[ :prevHeading

exmap togglefold obcommand editor:toggle-fold
exmap unfoldall obcommand editor:unfold-all
exmap foldall obcommand editor:fold-all
nmap za :togglefold
nmap zR :unfoldall
nmap zM :foldall

exmap openlink obcommand editor:open-link-in-new-leaf
" nmap \go :openlink
nmap <C-]> :openlink

exmap linkfollow obcommand editor:follow-link
exmap slinkfollow obcommand editor:open-link-in-new-split
nmap \gf :linkfollow
nmap \sgf :slinkfollow

" goto last edit location
nmap g; u<C-r>

" mapping vs/hs as workspace split
exmap vs obcommand workspace:split-vertical
exmap sp obcommand workspace:split-horizontal

" window controls
exmap w  obcommand editor:save-file
exmap q  obcommand workspace:close
exmap wq obcommand workspace:close

" focus
exmap focusLeft obcommand editor:focus-left
exmap focusRight obcommand editor:focus-right
exmap focusBottom obcommand editor:focus-bottom
exmap focusTop obcommand editor:focus-top
" <C-w> closes current tab
" nmap <C-w>h :focusLeft
" nmap <C-w>l :focusRight
" nmap <C-w>j :focusBottom
" nmap <C-w>k :focusTop
nmap \wh :focusLeft
nmap \wl :focusRight
nmap \wj :focusBottom
nmap \wk :focusTop

" Blockquote
exmap toggleBlockquote obcommand editor:toggle-blockquote
nmap \< :toggleBlockquote
nmap \> :toggleBlockquote


exmap new   obcommand file-explorer:new-file
exmap ed    obcommand switcher:open
exmap bn    obcommand workspace:next-tab
exmap bp    obcommand workspace:previous-tab
exmap trash obcommand workspace:show-trash

" editor:toggle-bold
" editor:toggle-italics
" editor:toggle-strikethrough
" editor:toggle-highlight
" editor:toggle-code
" editor:toggle-inline-math
" editor:toggle-blockquote

" FIXME:
" exmap comment obcommand editor:toggle-comments
" nmap \x :comment
" vnoremap \x :comment

" FIXME:
" exmap clear obcommand editor:clear-formatting
" nmap \cl :clear

" editor:toggle-bullet-list
" editor:toggle-numbered-list

exmap toggleTask obcommand editor:toggle-checklist-status
nmap \<Space> :toggleTask

" editor:cycle-list-checklist
exmap co    obcommand editor:insert-callout
exmap cb    obcommand editor:insert-codeblock
exmap hr    obcommand editor:insert-horizontal-rule
nmap \\ :hr
exmap math  obcommand editor:insert-mathblock
exmap table obcommand editor:insert-table
exmap time obcommand insert-current-time

" Available commands:
" editor:save-file
" editor:follow-link
" editor:open-link-in-new-leaf
" editor:open-link-in-new-window
" workspace:toggle-pin
" editor:open-link-in-new-split
" editor:focus-top
" editor:focus-bottom
" editor:focus-left
" editor:focus-right
" workspace:split-vertical
" workspace:split-horizontal
" workspace:toggle-stacked-tabs
" workspace:edit-file-title
" workspace:copy-path
" workspace:copy-url
" workspace:undo-close-pane
" workspace:export-pdf
" editor:rename-heading
" workspace:open-in-new-window
" workspace:move-to-new-window
" workspace:next-tab
" workspace:goto-tab-1
" workspace:goto-tab-2
" workspace:goto-tab-3
" workspace:goto-tab-4
" workspace:goto-tab-5
" workspace:goto-tab-6
" workspace:goto-tab-7
" workspace:goto-tab-8
" workspace:goto-last-tab
" workspace:previous-tab
" workspace:new-tab
" workspace:show-trash
" dataview:dataview-force-refresh-views
" dataview:dataview-drop-cache
" dataview:dataview-rebuild-current-view
" obsidian-excalidraw-plugin:excalidraw-convert-image-from-url-to-local-file
" obsidian-excalidraw-plugin:excalidraw-unzip-file
" obsidian-excalidraw-plugin:excalidraw-publish-svg-check
" obsidian-excalidraw-plugin:excalidraw-embeddable-poroperties
" obsidian-excalidraw-plugin:excalidraw-embeddables-relative-scale
" obsidian-excalidraw-plugin:open-image-excalidraw-source
" obsidian-excalidraw-plugin:excalidraw-disable-autosave
" obsidian-excalidraw-plugin:excalidraw-enable-autosave
" obsidian-excalidraw-plugin:excalidraw-download-lib
" obsidian-excalidraw-plugin:excalidraw-open
" obsidian-excalidraw-plugin:excalidraw-open-on-current
" obsidian-excalidraw-plugin:excalidraw-insert-transclusion
" obsidian-excalidraw-plugin:excalidraw-insert-last-active-transclusion
" obsidian-excalidraw-plugin:excalidraw-autocreate
" obsidian-excalidraw-plugin:excalidraw-autocreate-newtab
" obsidian-excalidraw-plugin:excalidraw-autocreate-on-current
" obsidian-excalidraw-plugin:excalidraw-autocreate-popout
" obsidian-excalidraw-plugin:excalidraw-autocreate-and-embed
" obsidian-excalidraw-plugin:excalidraw-autocreate-and-embed-new-tab
" obsidian-excalidraw-plugin:excalidraw-autocreate-and-embed-on-current
" obsidian-excalidraw-plugin:excalidraw-autocreate-and-embed-popout
" obsidian-excalidraw-plugin:run-ocr
" obsidian-excalidraw-plugin:rerun-ocr
" obsidian-excalidraw-plugin:run-ocr-selectedelements
" obsidian-excalidraw-plugin:search-text
" obsidian-excalidraw-plugin:fullscreen
" obsidian-excalidraw-plugin:disable-binding
" obsidian-excalidraw-plugin:disable-framerendering
" obsidian-excalidraw-plugin:disable-frameclipping
" obsidian-excalidraw-plugin:export-image
" obsidian-excalidraw-plugin:save
" obsidian-excalidraw-plugin:toggle-lock
" obsidian-excalidraw-plugin:scriptengine-store
" obsidian-excalidraw-plugin:delete-file
" obsidian-excalidraw-plugin:convert-text2MD
" obsidian-excalidraw-plugin:insert-link
" obsidian-excalidraw-plugin:insert-command
" obsidian-excalidraw-plugin:insert-link-to-element
" obsidian-excalidraw-plugin:insert-link-to-element-group
" obsidian-excalidraw-plugin:insert-link-to-element-frame
" obsidian-excalidraw-plugin:insert-link-to-element-area
" obsidian-excalidraw-plugin:toggle-lefthanded-mode
" obsidian-excalidraw-plugin:flip-image
" obsidian-excalidraw-plugin:reset-image-to-100
" obsidian-excalidraw-plugin:convert-card-to-file
" obsidian-excalidraw-plugin:insert-active-pdfpage
" obsidian-excalidraw-plugin:crop-image
" obsidian-excalidraw-plugin:annotate-image
" obsidian-excalidraw-plugin:insert-image
" obsidian-excalidraw-plugin:import-svg
" obsidian-excalidraw-plugin:release-notes
" obsidian-excalidraw-plugin:tray-mode
" obsidian-excalidraw-plugin:insert-md
" obsidian-excalidraw-plugin:insert-pdf
" obsidian-excalidraw-plugin:universal-add-file
" obsidian-excalidraw-plugin:universal-card
" obsidian-excalidraw-plugin:insert-LaTeX-symbol
" obsidian-excalidraw-plugin:toggle-excalidraw-view
" obsidian-excalidraw-plugin:convert-to-excalidraw
" obsidian-excalidraw-plugin:convert-excalidraw
" obsidian-map-view:open-map-view
" obsidian-map-view:convert-selection-to-location
" obsidian-map-view:insert-geolink
" obsidian-map-view:new-geolocation-note
" obsidian-map-view:add-frontmatter-geolocation
" obsidian-map-view:open-map-search
" obsidian-map-view:quick-map-embed
" obsidian-kanban:create-new-kanban-board
" obsidian-kanban:archive-completed-cards
" obsidian-kanban:toggle-kanban-view
" obsidian-kanban:convert-to-kanban
" obsidian-kanban:add-kanban-lane
" obsidian-kanban:view-board
" obsidian-kanban:view-table
" obsidian-kanban:view-list
" obsidian-kanban:open-board-settings
" table-editor-obsidian:next-row
" table-editor-obsidian:next-cell
" table-editor-obsidian:previous-cell
" table-editor-obsidian:format-table
" table-editor-obsidian:format-all-tables
" table-editor-obsidian:insert-column
" table-editor-obsidian:insert-row
" table-editor-obsidian:escape-table
" table-editor-obsidian:left-align-column
" table-editor-obsidian:center-align-column
" table-editor-obsidian:right-align-column
" table-editor-obsidian:move-column-left
" table-editor-obsidian:move-column-right
" table-editor-obsidian:move-row-up
" table-editor-obsidian:move-row-down
" table-editor-obsidian:delete-column
" table-editor-obsidian:delete-row
" table-editor-obsidian:sort-rows-ascending
" table-editor-obsidian:sort-rows-descending
" table-editor-obsidian:evaluate-formulas
" table-editor-obsidian:table-control-bar
" obsidian-advanced-slides:open-advanced-slides-preview
" obsidian-advanced-slides:reload-advanced-slides-preview
" obsidian-minimal-settings:increase-body-font-size
" obsidian-minimal-settings:decrease-body-font-size
" obsidian-minimal-settings:toggle-minimal-dark-cycle
" obsidian-minimal-settings:toggle-minimal-light-cycle
" obsidian-minimal-settings:toggle-hidden-borders
" obsidian-minimal-settings:toggle-colorful-headings
" obsidian-minimal-settings:toggle-minimal-focus-mode
" obsidian-minimal-settings:toggle-minimal-colorful-frame
" obsidian-minimal-settings:cycle-minimal-table-width
" obsidian-minimal-settings:cycle-minimal-image-width
" obsidian-minimal-settings:cycle-minimal-iframe-width
" obsidian-minimal-settings:cycle-minimal-chart-width
" obsidian-minimal-settings:cycle-minimal-map-width
" obsidian-minimal-settings:toggle-minimal-img-grid
" obsidian-minimal-settings:toggle-minimal-switch
" obsidian-minimal-settings:toggle-minimal-light-default
" obsidian-minimal-settings:toggle-minimal-light-white
" obsidian-minimal-settings:toggle-minimal-light-tonal
" obsidian-minimal-settings:toggle-minimal-light-contrast
" obsidian-minimal-settings:toggle-minimal-dark-default
" obsidian-minimal-settings:toggle-minimal-dark-tonal
" obsidian-minimal-settings:toggle-minimal-dark-black
" obsidian-minimal-settings:toggle-minimal-atom-light
" obsidian-minimal-settings:toggle-minimal-ayu-light
" obsidian-minimal-settings:toggle-minimal-catppuccin-light
" obsidian-minimal-settings:toggle-minimal-default-light
" obsidian-minimal-settings:toggle-minimal-gruvbox-light
" obsidian-minimal-settings:toggle-minimal-eink-light
" obsidian-minimal-settings:toggle-minimal-everforest-light
" obsidian-minimal-settings:toggle-minimal-flexoki-light
" obsidian-minimal-settings:toggle-minimal-macos-light
" obsidian-minimal-settings:toggle-minimal-notion-light
" obsidian-minimal-settings:toggle-minimal-nord-light
" obsidian-minimal-settings:toggle-minimal-rose-pine-light
" obsidian-minimal-settings:toggle-minimal-solarized-light
" obsidian-minimal-settings:toggle-minimal-things-light
" obsidian-minimal-settings:toggle-minimal-atom-dark
" obsidian-minimal-settings:toggle-minimal-ayu-dark
" obsidian-minimal-settings:toggle-minimal-catppuccin-dark
" obsidian-minimal-settings:toggle-minimal-dracula-dark
" obsidian-minimal-settings:toggle-minimal-default-dark
" obsidian-minimal-settings:toggle-minimal-eink-dark
" obsidian-minimal-settings:toggle-minimal-everforest-dark
" obsidian-minimal-settings:toggle-minimal-flexoki-dark
" obsidian-minimal-settings:toggle-minimal-gruvbox-dark
" obsidian-minimal-settings:toggle-minimal-macos-dark
" obsidian-minimal-settings:toggle-minimal-nord-dark
" obsidian-minimal-settings:toggle-minimal-notion-dark
" obsidian-minimal-settings:toggle-minimal-rose-pine-dark
" obsidian-minimal-settings:toggle-minimal-solarized-dark
" obsidian-minimal-settings:toggle-minimal-things-dark
" obsidian-minimal-settings:toggle-minimal-dev-block-width
" callout-manager:manage-callouts
" app:go-back
" app:go-forward
" app:open-vault
" theme:use-dark
" theme:use-light
" theme:switch
" app:open-settings
" app:show-release-notes
" markdown:toggle-preview
" markdown:add-metadata-property
" markdown:add-alias
" markdown:edit-metadata-property
" markdown:clear-metadata-properties
" workspace:close
" workspace:close-window
" workspace:close-others
" workspace:close-tab-group
" workspace:close-others-tab-group
" app:delete-file
" app:toggle-ribbon
" app:toggle-left-sidebar
" app:toggle-right-sidebar
" app:toggle-default-new-pane-mode
" app:open-help
" app:reload
" app:show-debug-info
" app:open-sandbox-vault
" window:toggle-always-on-top
" window:zoom-in
" window:zoom-out
" window:reset-zoom
" file-explorer:new-file
" file-explorer:new-file-in-current-tab
" file-explorer:new-file-in-new-pane
" open-with-default-app:open
" file-explorer:move-file
" file-explorer:duplicate-file
" open-with-default-app:show
" editor:toggle-source
" editor:open-search
" editor:open-search-replace
" editor:focus
" editor:toggle-fold-properties
" editor:toggle-fold
" editor:fold-all
" editor:unfold-all
" editor:fold-less
" editor:fold-more
" editor:insert-wikilink
" editor:insert-embed
" editor:insert-link
" editor:insert-tag
" editor:set-heading
" editor:set-heading-0
" editor:set-heading-1
" editor:set-heading-2
" editor:set-heading-3
" editor:set-heading-4
" editor:set-heading-5
" editor:set-heading-6
" editor:toggle-bold
" editor:toggle-italics
" editor:toggle-strikethrough
" editor:toggle-highlight
" editor:toggle-code
" editor:toggle-inline-math
" editor:toggle-blockquote
" editor:toggle-comments
" editor:clear-formatting
" editor:toggle-bullet-list
" editor:toggle-numbered-list
" editor:toggle-checklist-status
" editor:cycle-list-checklist
" editor:insert-callout
" editor:insert-codeblock
" editor:insert-horizontal-rule
" editor:insert-mathblock
" editor:insert-table
" editor:swap-line-up
" editor:swap-line-down
" editor:attach-file
" editor:delete-paragraph
" editor:add-cursor-below
" editor:add-cursor-above
" editor:toggle-spellcheck
" editor:table-row-before
" editor:table-row-after
" editor:table-row-up
" editor:table-row-down
" editor:table-row-copy
" editor:table-row-delete
" editor:table-col-before
" editor:table-col-after
" editor:table-col-left
" editor:table-col-right
" editor:table-col-copy
" editor:table-col-delete
" editor:table-col-align-left
" editor:table-col-align-center
" editor:table-col-align-right
" editor:context-menu
" file-explorer:open
" file-explorer:reveal-active-file
" file-explorer:new-folder
" global-search:open
" switcher:open
" graph:open
" graph:open-local
" graph:animate
" backlink:open
" backlink:open-backlinks
" backlink:toggle-backlinks-in-document
" canvas:new-file
" canvas:export-as-image
" canvas:jump-to-group
" canvas:convert-to-file
" outgoing-links:open
" outgoing-links:open-for-current
" tag-pane:open
" properties:open
" properties:open-local
" daily-notes
" daily-notes:goto-prev
" daily-notes:goto-next
" insert-template
" insert-current-date
" insert-current-time
" note-composer:merge-file
" note-composer:split-file
" note-composer:extract-heading
" command-palette:open
" bookmarks:open
" bookmarks:bookmark-current-view
" bookmarks:bookmark-current-search
" bookmarks:unbookmark-current-view
" bookmarks:bookmark-current-section
" bookmarks:bookmark-current-heading
" bookmarks:bookmark-all-tabs
" outline:open
" outline:open-for-current
" slides:start
" file-recovery:open
" obsidian-mindmap-nextgen:mindmapnextgen:unpinned
" obsidian-mindmap-nextgen:mindmapnextgen:pinned
