#{{{ Variables / Defaults
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=10000

PROJECT_BASE=~/Projects
#}}}

#{{{ Capability
shopt -s checkwinsize
shopt -s histappend
set -o vi
# bind 'set show-mode-in-prompt on'
# shopt -s dotglob nullglob #( include hidden files in globs, but []regex fails)
#}}}

#{{{ Util functions
function motd(){
	clear
	cat ~/.bash/motd 2>/dev/null
	if [[ $(command -v fortune) ]]; then
		fortune -a work people paradoxum -s -n 200 | fold -w 60 -s
	fi
}
#}}}

#{{{ Default color aliases
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi
#}}}

#{{{ User aliases and exports
[[ -f ~/.bash/aliases ]] && . ~/.bash/aliases
[[ -f ~/.bash/exports ]] && . ~/.bash/exports
#}}}

#{{{ External sourced files
source /etc/profile.d/vte.sh
[[ -z "$_PROJECT" ]] && _PROJECT=$DEFAULT_PROJECT
source /usr/share/bash-project-mod/project-mod && __init_project
source /usr/local/lib/altline
#}}}

motd

# vim:fdm=marker
