#!/usr/bin/env bash

shopt -s nullglob globstar

app_name="Password"
prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -p "$app_name")

[[ -n $password ]] || exit

pass show -c "$password" 2>/dev/null && \
	notify-send -a 'passmenu_rofi' "$app_name" "$password"
